import {calculateTotalCost} from './calculate.mjs';
export const money=n=>Math.round(n).toLocaleString('ko-KR')+'원';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function field(key,label,value=0,options={}) {const {unit='원',help='',max=100000000,type='money',required=true}=options;return `<label class="field ${options.full?'full':''}"><span>${esc(label)}${help?` <details class="help"><summary aria-label="${esc(label)} 설명">?</summary><p>${esc(help)}</p></details>`:''}</span><div class="input-unit"><input name="${key}" ${type==='text'?`type="text" maxlength="${max}" value="${esc(value)}"`:`type="text" inputmode="${type==='decimal'?'decimal':'numeric'}" data-number="${type}" data-max="${max}" value="${value===''?'':Number(value).toLocaleString('en-US',{maximumFractionDigits:2})}"`} ${required?'required':''} autocomplete="off" ${help?`aria-description="${esc(help)}"`:''}><span class="unit">${type==='text'?'':unit}</span></div></label>`;}
export function select(key,label,items,value,help='') {return `<label class="field"><span>${esc(label)}</span><select name="${key}">${items.map(([v,t])=>`<option value="${v}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select>${help?`<small>${esc(help)}</small>`:''}</label>`;}
const months=(key,label,value,help='')=>field(key,label,value,{unit:'개월',max:120,type:'integer',help});
const step=(n,title,body)=>`<section class="panel"><div class="step-title"><span class="step-num">${n}</span><h2>${title}</h2></div>${body}</section>`;
export function addonView(a,i){return `<div class="addon" data-addon="${i}"><div class="addon-head"><strong>부가서비스 ${i+1}</strong><button type="button" class="text-btn danger" data-remove-addon="${i}" aria-label="부가서비스 ${i+1} 삭제">삭제</button></div><div class="field-grid">${field('addonName'+i,'서비스 이름',a.name,{type:'text',max:80,full:true,required:false})}${field('addonCost'+i,'월 이용료',a.cost,{max:1000000})}${months('addonMonths'+i,'유지기간',a.months)}</div></div>`;}
export function editorView(q,cfg) {return `<form id="quote-form" novalidate><div class="editor-toolbar"><span class="small">계약서의 숫자를 순서대로 입력하세요.</span><div class="actions"><button type="button" id="sample" class="text-btn">예시 불러오기</button><button type="button" id="reset" class="text-btn">새 견적</button></div></div>
${step('01','휴대폰 정보',`<div class="field-grid">${field('name','견적 이름',q.name,{type:'text',max:80,full:true})}${field('model','휴대폰 모델명',q.model,{type:'text',max:100,full:true})}${field('retail','출고가 (참고)',q.retail)}${field('price','판매가격 또는 할부원금',q.price)}${select('priceMode','입력한 기기 가격 기준',[['net','할인 후 최종 원금'],['gross','할인 전 판매가격']],q.priceMode)}${field('deviceDiscount','기기 할인금액',q.deviceDiscount,{help:'할인 전 가격 모드에서만 차감합니다. 최종 원금 모드에서는 참고 내역입니다.'})}</div><p class="info-note">이미 지원금이 빠진 할부원금이라면 <strong>할인 후 최종 원금</strong>을 선택하세요. 지원금을 다시 빼지 않습니다.</p>`)}
${step('02','구매방식',`<div class="field-grid">${select('method','어디서, 어떤 조건으로 구매하나요?',[['unlocked','자급제'],['subsidy',cfg.policy.subsidyLabel+' 방식'],['contract','선택약정'],['other','기타 판매점 견적']],q.method)}</div>`)}
${step('03','지원 및 할인',`<div class="field-grid">${field('subsidy',cfg.policy.subsidyLabel,q.subsidy,{help:'통신사 제공 기기 지원금입니다. 선택약정과 중복 적용하지 않습니다.'})}${field('extra','판매점 추가지원금',q.extra,{help:'판매점이 별도로 제공하는 확정된 기기 할인. 통신사 지원금과 구분하세요.'})}${field('coupon','쿠폰 / 프로모션 할인',q.coupon,{help:'기기 구매 시 즉시 적용되는 할인입니다. 월 요금 프로모션은 요금제에 입력하세요.'})}${field('other','기타 기기 할인',q.other,{help:'위 항목에 포함하지 않은 확정된 즉시 할인입니다. 미래 반납 보상은 제외하세요.'})}${field('card','카드 월 청구할인',q.card,{max:1000000,help:'매월 실적 조건 충족을 가정한 혜택입니다. 기본 기기 할인에 중복 포함하지 마세요.'})}${months('cardMonths','카드 할인 적용기간',q.cardMonths)}${field('cardFee','카드 연회비',q.cardFee,{max:10000000,help:'카드 할인 적용기간의 1·13·25개월에 청구한다고 가정합니다. 추가 소비 비용은 제외합니다.'})}</div><p class="hint">카드 실적을 채우기 위한 소비와 불확실한 페이백은 포함하지 않습니다. 카드 할인 0원인 견적과도 비교하세요.</p>`)}
${step('04','요금제와 유지기간',`<div class="field-grid">${field('plan','초기 요금제 월정액',q.plan,{max:10000000,help:'부가세 포함, 선택약정 할인 전 대상 월정액을 입력하세요.'})}${months('hold','초기 요금제 유지기간',q.hold,'0개월이면 첫 달부터 이후 요금제를 사용합니다.')}${field('laterPlan','유지기간 이후 월정액',q.laterPlan,{max:10000000,full:true})}</div><p class="hint">예: 6개월 유지 → 1~6개월은 초기 요금, 7개월부터 이후 요금. 요금제가 같으면 두 월정액을 같게 입력하세요.</p>`)}
${step('05','선택약정',`<div class="field-grid">${select('discount','선택약정 사용',[['false','사용 안 함'],['true','선택약정 적용']],q.discount)}${months('discountMonths','할인 적용기간',q.discountMonths,'36개월 계산 시 재약정을 가정하려면 36개월로 변경하세요.')}</div><details><summary class="small">고급 설정 · 할인율 직접 수정</summary><div class="field-grid">${field('discountRate','선택약정 할인율',q.discountRate,{unit:'%',max:100,type:'decimal'})}</div></details><p class="hint">기본 ${cfg.policy.discountRate}% · 보험·부가서비스·기기 할부금은 할인 대상에서 제외합니다.</p>`)}
${step('06','부가서비스',`<div id="addons">${q.addons.map(addonView).join('')}</div><button type="button" id="add-addon">＋ 부가서비스 추가</button><p class="hint">서비스별 월 이용료와 유지 개월 수를 따로 계산합니다.</p>`)}
${step('07','휴대폰 보험',`<div class="field-grid">${field('insurance','월 보험료',q.insurance,{max:1000000})}${months('insuranceMonths','가입기간',q.insuranceMonths)}</div>`)}
${step('08','할부',`<div class="field-grid">${select('termPreset','납부 방식',[[0,'일시불'],[12,'12개월'],[24,'24개월'],[30,'30개월'],[36,'36개월'],['custom','직접입력']],[0,12,24,30,36].includes(q.term)?q.term:'custom')}${months('term','할부 기간 (0 = 일시불)',q.term)}${select('feeMode','할부 비용 입력 방식',[['apr','연이율 · 원리금균등'],['flat','총 수수료 직접입력']],q.feeMode)}${field('apr','연 이율',q.apr,{unit:'%',max:100,type:'decimal'})}${field('flatFee','총 할부 수수료',q.flatFee)}</div><div class="actions" style="margin-top:12px"><button type="button" id="zero-interest" class="text-btn">0% 무이자로 설정</button></div><p class="hint">연이율 모드는 원리금균등, 총 수수료 모드는 원금·수수료 균등 배분으로 예상합니다. 일시불에는 수수료가 적용되지 않습니다. 실제 청구 방식과 반올림은 계약서를 확인하세요.</p>`)}
<div id="form-errors" class="error-box" role="alert" tabindex="-1"></div><button type="submit" class="primary" style="width:100%;min-height:56px">내 견적 분석하기 <span aria-hidden="true">→</span></button></form>`;}
export function resultView(q,period=24){const r=calculateTotalCost(q,period),other=calculateTotalCost(q,period===24?36:24);const parts=[['기기값',r.device,'#087a72'],['통신요금',r.plan,'#76b4a8'],['부가서비스',r.addons,'#577ed0'],['보험',r.insurance,'#d39b3e'],['할부 비용',r.interest,'#9a83bd'],['카드 연회비',r.cardFee,'#738690']];const positive=parts.reduce((s,p)=>s+p[1],0);let cursor=0;const gradient=parts.map(p=>{const start=cursor;cursor+=positive?p[1]/positive*100:0;return `${p[2]} ${start}% ${cursor}%`;}).join(',');return `<div class="section-head"><h2>내 견적 분석</h2><div class="segmented" aria-label="분석 기간"><button data-period="24" class="${period===24?'active':''}" aria-pressed="${period===24}">24개월</button><button data-period="36" class="${period===36?'active':''}" aria-pressed="${period===36}">36개월</button></div></div><div id="dirty"></div>
<section class="panel result-main"><span class="eyebrow">YOUR COST, CLEARLY</span><h2>${period}개월 실제 총비용</h2><div class="big-money">${money(r.total)}</div><p class="hint">${esc(q.model)} · ${esc(q.name)}</p><div class="receipt-row"><span>월평균 실제 부담액</span><strong>${money(r.average)}</strong></div><p class="hint">${other.months}개월 기준 ${money(other.total)} · 월평균 ${money(other.average)}</p></section>
${r.remaining?`<div class="info-note warning"><strong>남은 할부원금 ${money(r.remaining)} 포함</strong><br>${period}개월 실제 지출 ${money(r.cash)}에 남은 원금을 더한 비교 총비용입니다. 이후 발생할 할부 이자 ${money(r.futureFee)}는 이 합계에 포함하지 않습니다. 조기 상환 수수료는 별도입니다.</div>`:''}
${q.card?`<p class="info-note warning">카드 실적 충족을 가정한 할인 ${money(r.card)}을 반영했습니다. 실적 소비는 제외되며, 카드 할인 제외 시 총비용은 ${money(r.total+r.card)}입니다.</p>`:''}
<section class="panel"><h2>비용은 어디에 쓰일까요?</h2><div class="breakdown"><div class="donut" role="img" aria-label="항목별 비용 비중, 아래 목록에 수치 제공" style="background:${positive?`conic-gradient(${gradient})`:'#edf1f3'}"><div class="donut-hole">비용 구성</div></div><ul class="legend">${parts.map(([label,n,color])=>`<li><span><i style="background:${color}"></i>${label}</span><strong>${positive?(n/positive*100).toFixed(1):0}%</strong></li>`).join('')}</ul></div><p class="hint">카드 청구할인 차감 전 양수 비용 기준입니다.</p><div class="result-stats">${parts.map(([label,n])=>`<div class="stat"><span>${label}</span><strong>${money(n)}</strong></div>`).join('')}<div class="stat"><span>받은 할인 총액</span><strong>${money(r.discounts)}</strong></div><div class="stat"><span>기간 내 실제 지출</span><strong>${money(r.cash)}</strong></div></div><p class="hint">할인 합계는 기기 할인 + 선택약정 + 카드 혜택입니다. 최종 원금 모드의 기기 할인은 출고가와 원금의 양수 차이로 추정하며, 총비용에서 다시 빼지 않습니다.</p></section>
<section class="panel"><h2>숫자로 읽는 내 견적</h2><ul class="result-summary"><li>${period}개월 총비용은 ${money(r.total)}입니다.</li><li>카드 할인 전 비용 중 통신요금은 ${positive?(r.plan/positive*100).toFixed(1):0}%입니다.</li><li>초기 요금제 유지로 이후 요금제 대비 더 내는 금액은 ${money(r.premium)}입니다.</li><li>부가서비스 유지비는 총 ${money(r.addons)}입니다.</li><li>선택약정 ${q.discount?`${q.discountMonths}개월 적용 가정`:'미적용'}입니다.</li></ul><div class="actions"><button data-action="save" class="primary">견적 저장</button><button data-action="compare">비교에 추가</button></div><div class="actions" style="margin-top:10px"><button data-action="link">링크 복사</button><button data-action="text">결과 텍스트</button><button data-action="image">이미지 저장</button></div><p class="hint">공유 링크에는 견적 이름·모델명·서비스 이름 없이 계산 숫자만 포함합니다.</p></section>
<section class="panel"><h2>월별 지출 변화</h2><p class="small">일시불 기기값은 1개월차에 포함합니다.</p>${chartView(r.rows)}<p class="hint">${q.hold>0&&q.hold<period?`${q.hold+1}개월부터 이후 요금제로 계산합니다.`:'입력한 요금 유지기간을 반영했습니다.'} 남은 할부원금은 월별 지출에 더하지 않습니다.</p></section>
<section class="panel"><h2>월별 비용표</h2><div class="table-scroll" tabindex="0" role="region" aria-label="월별 비용표, 가로 스크롤 가능"><table><caption>${period}개월 실제 지출 · 원 단위</caption><thead><tr>${['월','기기 원금','할부 비용','통신비','부가서비스','보험','카드 순비용','합계'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${r.rows.map(x=>`<tr class="${x.month===q.hold+1?'row-change':''}"><th scope="row">${x.month}개월</th>${[x.device,x.interest,x.plan,x.addons,x.insurance,x.cardFee-x.card,x.total].map(v=>`<td>${money(v)}</td>`).join('')}</tr>`).join('')}</tbody><tfoot><tr><th scope="row">기간 지출 합계</th><td colspan="7">${money(r.cash)}</td></tr></tfoot></table></div></section>`;}
function chartView(rows){const max=Math.max(1,...rows.map(r=>r.total)),min=Math.min(0,...rows.map(r=>r.total)),range=max-min;const y=v=>170-(v-min)/range*140;const pts=rows.map((r,i)=>`${55+i/(rows.length-1)*325},${y(r.total)}`).join(' ');return `<div class="chart-wrap"><svg class="month-chart" viewBox="0 0 410 215" role="img" aria-label="월별 지출 선 그래프. 정확한 값은 아래 월별 표를 확인하세요."><line x1="55" y1="30" x2="385" y2="30" stroke="#e0e8ea"/><line x1="55" y1="100" x2="385" y2="100" stroke="#e0e8ea"/><line x1="55" y1="170" x2="385" y2="170" stroke="#e0e8ea"/><text x="0" y="34" fill="#61717b" font-size="11">${(max/10000).toFixed(1)}만</text><text x="0" y="174" fill="#61717b" font-size="11">${(min/10000).toFixed(1)}만</text><polyline points="${pts}" fill="none" stroke="#087a72" stroke-width="3" stroke-linejoin="round"/>${rows.map((r,i)=>`<circle cx="${55+i/(rows.length-1)*325}" cy="${y(r.total)}" r="2.5" fill="#087a72"><title>${r.month}개월: ${money(r.total)}</title></circle>`).join('')}<text x="55" y="201" fill="#61717b" font-size="12">1개월</text><text x="350" y="201" fill="#61717b" font-size="12">${rows.length}개월</text></svg></div>`;}
